### ISSUE TITLE
Add proper packaging

### ISSUE THREAD

**Issue by prologic** [ngzhian/colordiffs#2]
- [x] Add a `setup.py`
- [x] Add an entry-point so the script becomes `colordiffs`
- [x] Fix `long_desciprtion` so it renders on PyPi proper.y. Use `python setup.py --long-description | rst2html.py` from [docutils](https://pypi.python.org/pypi/docutils)

**Comment by ngzhian** [comment]
@prologic thanks for setting up this checklist! i'm slowing ticking them away :P

**Comment by prologic** [comment]
Haha no worries! Let me know if you need any help or a template to follow, etc :)

**Comment by ngzhian** [comment]
@prologic wow, had so much trouble packaging the script haha, but it should work fine now! after pip install you should be able to run `colordiffs` from the command line and the example will work fine! (provided you are in a proper git repo) gonna close this thanks!

**Comment by prologic** [comment]
Don't forget about the `long-description` too and publish a new version up to PyPi using your new `python setup.py register bdist_wheel upload` facilities :)

**Comment by prologic** [comment]
And good job :+1: I think I'll use this tool a LOT!

**Comment by ngzhian** [comment]
@prologic that should be fixed quite nicely now https://pypi.python.org/pypi/colordiffs
I'm glad to hear that :D  Pretty sure there are tons of bugs around, will continue polishing this up over time

**Comment by prologic** [comment]
Beautiful! :+1:
